In [3]:
import math

# Sigmoid activation
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

# Input vector
x1, x2 = 0.05, 0.10  # example values

# Weights and biases (manually defined)
w_input_hidden = [[0.15, 0.20],  # weights to hidden neuron 1 from inputs
                  [0.25, 0.30]]  # weights to hidden neuron 2 from inputs
bias_hidden = [0.35, 0.35]

w_hidden_output = [0.40, 0.45]  # weights to output neuron from hidden neurons
bias_output = 0.60

# Hidden layer calculations
net_h1 = x1 * w_input_hidden[0][0] + x2 * w_input_hidden[0][1] + bias_hidden[0]
out_h1 = sigmoid(net_h1)

net_h2 = x1 * w_input_hidden[1][0] + x2 * w_input_hidden[1][1] + bias_hidden[1]
out_h2 = sigmoid(net_h2)

# Output layer calculation
net_o1 = out_h1 * w_hidden_output[0] + out_h2 * w_hidden_output[1] + bias_output
out_o1 = sigmoid(net_o1)

# Print results
print(f"Hidden Neuron 1: net={net_h1:.4f}, out={out_h1:.4f}")
print(f"Hidden Neuron 2: net={net_h2:.4f}, out={out_h2:.4f}")
print(f"Output Neuron: net={net_o1:.4f}, out={out_o1:.4f}")


Hidden Neuron 1: net=0.3775, out=0.5933
Hidden Neuron 2: net=0.3925, out=0.5969
Output Neuron: net=1.1059, out=0.7514


In [21]:
import numpy as np

def perceptron_train(X, y, learning_rate=1.0, epochs=10):
    X = np.c_[np.ones(X.shape[0]), X]  # add bias input x0=1
    weights = np.zeros(X.shape[1])
    
    for epoch in range(epochs):
        print(f"\nEpoch {epoch+1}")
        errors = 0
        for xi, target in zip(X, y):
            net = np.dot(xi, weights)
            pred = 1 if net >= 0 else 0
            error = target - pred 
            update = learning_rate * (target - pred)
            weights += update * xi
            print(f"Input: {xi}, Target: {target}, Pred: {pred}, Error: {error}, Weights: {weights}")
            errors += int(update != 0)
        if errors == 0:
            break
    return weights

def perceptron_predict(X, weights):
    X = np.c_[np.ones(X.shape[0]), X]
    return [1 if np.dot(xi, weights) >= 0 else 0 for xi in X]

# Truth tables
AND_X = np.array([[0,0],[0,1],[1,0],[1,1]])
AND_y = np.array([0,0,0,1])

OR_X = np.array([[0,0],[0,1],[1,0],[1,1]])
OR_y = np.array([0,1,1,1])

XOR_X = np.array([[0,0],[0,1],[1,0],[1,1]])
XOR_y = np.array([0,1,1,0])

# Train
print("=== AND Gate ===")
w_and = perceptron_train(AND_X, AND_y)
print("Final Weights:", w_and)
print("Predictions:", perceptron_predict(AND_X, w_and))

print("\n=== OR Gate ===")
w_or = perceptron_train(OR_X, OR_y)
print("Final Weights:", w_or)
print("Predictions:", perceptron_predict(OR_X, w_or))

print("\n=== XOR Gate === (will not converge)")
w_xor = perceptron_train(XOR_X, XOR_y, epochs=10)
print("Final Weights:", w_xor)
print("Predictions:", perceptron_predict(XOR_X, w_xor))
print("Observation: XOR is not linearly separable, so perceptron fails to learn it.")


=== AND Gate ===

Epoch 1
Input: [1. 0. 0.], Target: 0, Pred: 1, Error: -1, Weights: [-1.  0.  0.]
Input: [1. 0. 1.], Target: 0, Pred: 0, Error: 0, Weights: [-1.  0.  0.]
Input: [1. 1. 0.], Target: 0, Pred: 0, Error: 0, Weights: [-1.  0.  0.]
Input: [1. 1. 1.], Target: 1, Pred: 0, Error: 1, Weights: [0. 1. 1.]

Epoch 2
Input: [1. 0. 0.], Target: 0, Pred: 1, Error: -1, Weights: [-1.  1.  1.]
Input: [1. 0. 1.], Target: 0, Pred: 1, Error: -1, Weights: [-2.  1.  0.]
Input: [1. 1. 0.], Target: 0, Pred: 0, Error: 0, Weights: [-2.  1.  0.]
Input: [1. 1. 1.], Target: 1, Pred: 0, Error: 1, Weights: [-1.  2.  1.]

Epoch 3
Input: [1. 0. 0.], Target: 0, Pred: 0, Error: 0, Weights: [-1.  2.  1.]
Input: [1. 0. 1.], Target: 0, Pred: 1, Error: -1, Weights: [-2.  2.  0.]
Input: [1. 1. 0.], Target: 0, Pred: 1, Error: -1, Weights: [-3.  1.  0.]
Input: [1. 1. 1.], Target: 1, Pred: 0, Error: 1, Weights: [-2.  2.  1.]

Epoch 4
Input: [1. 0. 0.], Target: 0, Pred: 0, Error: 0, Weights: [-2.  2.  1.]
Input: [1

In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# XOR inputs and outputs
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

np.random.seed(42)
input_neurons = 2
hidden_neurons = 2
output_neurons = 1

# Initialize weights and biases
W_input_hidden = np.random.uniform(size=(input_neurons, hidden_neurons))
B_hidden = np.random.uniform(size=(1, hidden_neurons))
W_hidden_output = np.random.uniform(size=(hidden_neurons, output_neurons))
B_output = np.random.uniform(size=(1, output_neurons))

lr = 0.5
epochs = 10000

for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X, W_input_hidden) + B_hidden
    hidden_output = sigmoid(hidden_input)
    
    final_input = np.dot(hidden_output, W_hidden_output) + B_output
    final_output = sigmoid(final_input)
    
    # Backpropagation
    error = y - final_output
    d_output = error * sigmoid_derivative(final_output)
    
    error_hidden = d_output.dot(W_hidden_output.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)
    
    # Update weights and biases
    W_hidden_output += hidden_output.T.dot(d_output) * lr
    B_output += np.sum(d_output, axis=0, keepdims=True) * lr
    W_input_hidden += X.T.dot(d_hidden) * lr
    B_hidden += np.sum(d_hidden, axis=0, keepdims=True) * lr

# Predictions
print("\nTrained Output for XOR:")
print(final_output)



Trained Output for XOR:
[[0.01890475]
 [0.98371361]
 [0.98369334]
 [0.01686123]]


In [16]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# Normalize input features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# One-hot encode output labels (compatible with older scikit-learn)
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(3, activation='softmax')
])

# Compile model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train model
history = model.fit(X_train, y_train, epochs=50, verbose=0)

# Training accuracy
train_loss, train_acc = model.evaluate(X_train, y_train, verbose=0)
print(f"Training Accuracy: {train_acc:.4f}")

# Test accuracy
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {test_acc:.4f}")

# Confusion matrix
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:\n", cm)


C:\Users\smani\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training Accuracy: 0.7750
Test Accuracy: 0.9000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
Confusion Matrix:
 [[10  0  0]
 [ 0  6  3]
 [ 0  0 11]]


In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load data
iris = load_iris()
X = iris.data
y = iris.target

# Normalize
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Convert to tensors
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

# Model
class IrisNet(nn.Module):
    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, 8)
        self.fc2 = nn.Linear(8, 3)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = IrisNet()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Train
for epoch in range(100):
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()

# Test accuracy
with torch.no_grad():
    preds = model(X_test)
    _, predicted = torch.max(preds, 1)
    acc = (predicted == y_test).float().mean()
    print(f"PyTorch Test Accuracy: {acc:.4f}")


PyTorch Test Accuracy: 0.9667


In [6]:
pip install torch

   ---------------------------------------- 0.0/241.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/241.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/241.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/241.4 MB ? eta -:--:--
   ---------------------------------------- 0.5/241.4 MB 728.2 kB/s eta 0:05:31
   ---------------------------------------- 0.5/241.4 MB 728.2 kB/s eta 0:05:31
   ---------------------------------------- 0.8/241.4 MB 729.2 kB/s eta 0:05:30
   ---------------------------------------- 1.0/241.4 MB 739.8 kB/s eta 0:05:25
   ---------------------------------------- 1.0/241.4 MB 739.8 kB/s eta 0:05:25
   ---------------------------------------- 1.3/241.4 MB 737.4 kB/s eta 0:05:26
   ---------------------------------------- 1.3/241.4 MB 737.4 kB/s eta 0:05:26
   ---------------------------------------- 1.6/241.4 MB 710.8 kB/s eta 0:05:38
   ---------------------------------------- 1.8/241.4 MB 718.9 kB/s eta 0:05


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


   ----------------- -------------------- 114.0/241.4 MB 658.8 kB/s eta 0:03:14
   ----------------- -------------------- 114.3/241.4 MB 659.8 kB/s eta 0:03:13
   ----------------- -------------------- 114.3/241.4 MB 659.8 kB/s eta 0:03:13
   ------------------ ------------------- 114.6/241.4 MB 660.2 kB/s eta 0:03:13
   ------------------ ------------------- 114.8/241.4 MB 660.9 kB/s eta 0:03:12
   ------------------ ------------------- 114.8/241.4 MB 660.9 kB/s eta 0:03:12
   ------------------ ------------------- 115.1/241.4 MB 660.2 kB/s eta 0:03:12
   ------------------ ------------------- 115.3/241.4 MB 661.9 kB/s eta 0:03:11
   ------------------ ------------------- 115.3/241.4 MB 661.9 kB/s eta 0:03:11
   ------------------ ------------------- 115.6/241.4 MB 661.9 kB/s eta 0:03:10
   ------------------ ------------------- 115.9/241.4 MB 663.7 kB/s eta 0:03:10
   ------------------ ------------------- 115.9/241.4 MB 663.7 kB/s eta 0:03:10
   ------------------ ------------------

In [1]:
import numpy as np

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Feedforward Neural Network class
class FeedforwardNN:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.5):
        self.learning_rate = learning_rate
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.bias_hidden = np.random.rand(hidden_size)
        self.weights_hidden_output = np.random.rand(hidden_size, output_size)
        self.bias_output = np.random.rand(output_size)

    def forward(self, X):
        self.hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = sigmoid(self.hidden_input)
        self.final_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        self.final_output = sigmoid(self.final_input)
        return self.final_output

    def backward(self, X, y):
        output_error = y - self.final_output
        output_delta = output_error * sigmoid_derivative(self.final_output)

        hidden_error = output_delta.dot(self.weights_hidden_output.T)
        hidden_delta = hidden_error * sigmoid_derivative(self.hidden_output)

        # Update weights and biases
        self.weights_hidden_output += self.hidden_output.T.dot(output_delta) * self.learning_rate
        self.bias_output += np.sum(output_delta, axis=0) * self.learning_rate
        self.weights_input_hidden += X.T.dot(hidden_delta) * self.learning_rate
        self.bias_hidden += np.sum(hidden_delta, axis=0) * self.learning_rate

    def train(self, X, y, epochs):
        for epoch in range(epochs):
            self.forward(X)
            self.backward(X, y)

# Input and output for XOR gate
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Create and train the neural network
nn = FeedforwardNN(input_size=2, hidden_size=2, output_size=1)
nn.train(X, y, epochs=10000)

# Test the neural network
print("Final Outputs after training:")
for x in X:
    print(f"Input: {x}, Predicted Output: {nn.forward(x.reshape(1, -1))}")


Final Outputs after training:
Input: [0 0], Predicted Output: [[0.0191913]]
Input: [0 1], Predicted Output: [[0.98333666]]
Input: [1 0], Predicted Output: [[0.98334045]]
Input: [1 1], Predicted Output: [[0.01734826]]
